### PR TITLE
Update package.json - added module - fix vite esm build

### PR DESCRIPTION
**Pull request by salvoravida**
Update package.json - added module - fix vite esm build

- - -
This change is [Reviewable](https://reviewable.io/reviews/louisbarranqueiro/reapop/506)

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
👋 @salvoravida Could you please share more information about this fix? What's the context?

**Comment by salvoravida** [comment]
without  "module": "dist/reapop.esm.js",
inside package.json
modern bundlers like VITE cannot use the esm build (not the commonJS one (main)) 
and so the bundle is not working.

that's all.

**Comment by salvoravida** [comment]
the node_env=production is an optimizaiton for the esm build -> https://tsdx.io/optimization

**Comment by ReidBraswell** [comment]
@salvoravida also using vite with a react app and seeing the following runtime error:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

I'd imagine your fix should help as the default import is not what is expected?

**Comment by salvoravida** [comment]
> @salvoravida also using vite with a react app and seeing the following runtime error:
> 
> ```
> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
> ```
> 
> I'd imagine your fix should help as the default import is not what is expected?

I dnk, anyway can test my current fork with the fix

@salvoravida/reapop 4.2.1

https://www.npmjs.com/package/@salvoravida/reapop

**Comment by salvoravida** [comment]
@LouisBarranqueiro any updates on this?

**Comment by LouisBarranqueiro** [comment]
👋 @salvoravida, sorry for the VERY VERY late reply.

> For ESM build, it's up to end-user to build environment specific build with NODE_ENV

I compared builds with and without it and it's the same. I will keep it just in case and check for newer versions if there is a difference.

Thanks for the contribution 🙏

**Review by LouisBarranqueiro — APPROVED** [review]
code :lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/louisbarranqueiro/reapop/506#-:-NJsil9k4ASxV1oyvh_Z:b-u7i93u)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @salvoravida)

**Review by LouisBarranqueiro — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/louisbarranqueiro/reapop/506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @salvoravida)

**Comment by LouisBarranqueiro** [comment]
I will update other dependencies and release a new version this WE 🙂

**Pull request merged**
