### PR TITLE
Enable React warning when no theme is specified

### PR DESCRIPTION
**Pull request by peteruithoven**

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
Hey @peteruithoven, you are the 1st contributor :) Thanks!

**Comment by LouisBarranqueiro** [comment]
I'm gonna add test cases to check that propTypes are required

**Comment by peteruithoven** [comment]
Nice! Glad to be of help

**Comment by LouisBarranqueiro** [comment]
Yeah, your commit allow me to notice that others props should be required, i'm goona fix that :)

**Pull request merged**
